# Generated by Django 4.1.5 on 2023-05-02 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="passenger_name",
            field=models.CharField(default="", max_length=255),
        ),
    ]
